### ISSUE TITLE
filelist.xml.z下载不成功

### ISSUE THREAD

**Issue by hbprotoss** [iFrankYang/DEPRECATED-PluginManager#1]
显示"文件列表下载完毕.正在解析..."的时候，interface下面并没有filelist.xml.z，手工用浏览器下下来之后放到interface下能正常更新，是QNetworkAccessManager不太靠谱吗？

**Comment by iFrankYang** [comment]
时隔两年……重启这个项目：https://gitlab.com/FrankYang/AddonBox
